config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => :registrations 
  

  resources :patients do
    collection { post :import }

  end

  root to: 'patients#index'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
    #  attr_accessor :nama, :no_kamar, :no_rm

    # def attr_names
    #   [nama, no_kamar, no_rm]
    # end

    def self.to_csv(options = {})
        CSV.generate(options) do |csv|
            csv << column_names
            all.each do |patient|
                csv << patient.attributes.values_at(*column_names)
            end
        end
    end

    def self.import(file)
        spreadsheet = open_spreadsheet(file)
        header = spreadsheet.row(1)
        (2..spreadsheet.last_row).each do |i|
          row = Hash[[header, spreadsheet.row(i)].transpose]
          patient = find_by_id(row["id"]) || new
          patient.attributes = row.to_hash.slice(*row.to_hash.keys)
          patient.save!
        end
      end
      
      def self.open_spreadsheet(file)
        case File.extname(file.original_filename)
         when '.csv' then Roo::Csv.new(file.path, nil, :ignore)
         when '.xls' then Roo::Excel.new(file.path,  packed: nil, file_warning: :ignore)
         when ".xlsx" then Roo::Excelx.new(file.path, packed: nil, file_warning: :ignore)
         else raise "Unknown file type: #{file.original_filename}"
        end
      end

      def self.search(search)
        if search
          where('name LIKE ?', "%#{search}%")
        else
          scoped
        end
      end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    layout :layout_by_resource

    private

    def layout_by_resource
        if devise_controller?
            "devise"
        else 
            "application"
        end
    end



end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /patients
  # GET /patients.json
  def index
    @search = Patient.ransack(params[:q])
    @patients = @search.result.paginate(:per_page => 5, :page => params[:page])
    # @patients = Patient.all.paginate(:per_page => 5, :page => params[:page])
    # filename = 
    respond_to do |format|
      format.html
      format.json { render json: PatientsDatatable.new(view_context) }
      format.csv { send_data @patients.to_csv }
      format.xls { headers["Content-Disposition"] = "attachment; filename=\"#{tes.xls}\"" }
    end
  end

  def import
    Patient.import(params[:file])
    redirect_to root_url, notice: "successfully"
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:nama, :no_kamar, :no_rm)
    end

    def sort_column
      Patient.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/_navbar.html.erb
 <nav class="navbar navbar-dark sticky-top bg-info flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">RSUP dr. J. Leimena</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "text-light" %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> |
        <%= link_to "Login", new_user_session_path %>
      <% end %>
    </li>
  </ul>
</nav>

app/views/layouts/_sidebar.html.erb
 <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="<%= root_path %> ">
              <span data-feather="home"></span>
              Dashboard <span class="sr-only">(current)</span>
            </a>
          </li>
          
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Quick reports</span>
          <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Total Pasien <span class="badge bg-warning badge-pill badge-warning">11</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Pasien dirawat <span class="badge bg-warning badge-pill badge-warning">11</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Pasien Rujukan <span class="badge bg-warning badge-pill badge-warning">11</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Pasien Sembuh <span class="badge bg-warning badge-pill badge-warning">11</span>
            </a>
          </li>
        </ul>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RCovid19</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js" %>
  </head>

  <body>
    <%= render  "layouts/navbar" %>
    <div class="container-fluid">
      <div class="row">
        <%= render  "layouts/sidebar" %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RCovid19</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js" %>
  </head>

  <body>

        <%= yield %>

  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nama %>
    <%= form.text_field :nama, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :no_kamar %>
    <%= form.text_field :no_kamar, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :no_rm %>
    <%= form.text_field :no_rm, class: "form-control" %>
  </div>

    <br>
    <%= form.submit class: "btn btn-primary" %>

<% end %>

app/views/patients/edit.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
    <h1>Editing Patient</h1>

    <%= render 'form', patient: @patient %>

    <%= link_to 'Show', @patient %> |
    <%= link_to 'Back', patients_path %>
</main>

app/views/patients/index.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
 <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Data Pasien Covid-19</h1>
  <p id="notice"><%= notice %></p>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
      <div class="btn btn-sm btn-outline-secondary">Export</div>
      <%= link_to "CSV", patients_path(format: "csv"), class: "btn btn-sm btn-outline-secondary" %> 
      <%= link_to "Excel", patients_path(format: "xls"), class: "btn btn-sm btn-outline-secondary" %>
    </div>
    <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
      <span data-feather="calendar"></span>
      This week 
    </button>
  </div>
</div>
   
<div class="container">
  <div class="row">
      <div class="col col-sm-3">
      <%= search_form_for @search do |f| %>
        <div class="form-group">
          <%= f.label :nama_cont, "Nama Pasien" %>
          <%= f.text_field :nama_cont, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :no_rm_cont, "No. RM" %>
          <%= f.text_field :no_rm_cont, class: "form-control" %>
        </div>
      </div>

      <div class="col col-sm-2">
        <div class="form-group">
          <%= f.label :tgl_masuk_cont, "Tanggal Masuk" %>
          <%= f.text_field :tgl_masuk_cont, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :tgl_keluar_cont, "Tanggal Keluar" %>
          <%= f.text_field :tgl_keluar_cont, class: "form-control" %>
        </div>
      </div>

  </div>
  <br>
  <div class="row">
    <div class="col col-sm-4">
       <%= f.submit "Search", class: "btn btn-primary btn-sm" %>
      <% end %> 
          <%= link_to "Reset", root_path, class:"btn btn-danger btn-sm" %>
    </div>
  </div>
</div>

<hr>

 <%= will_paginate  %> 

 <div class="table-responsive"> 
  <table id="dttb" class="table table-striped table-sm table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nama</th>
      <th>No kamar</th>
      <th>No RM</th>
      <th>Nik</th>
      <th>Tanggal Lahir</th>
      <th>No. Hp</th>
      <th>Agama/th>
      <th>Jenis Kelamin</th>
      <th>Alamat</th>
      <th>Pekerjaan</th>
      <th>Tanggal Masuk</th>
      <th>Tanggal Keluar</th>
      <th>Diagnosa</th>
      <th>Komorbid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @patients.each do |sortable| %>
      <tr>
        <td><%= sortable.id %></td>
        <td><%= sortable.nama %></td>
        <td><%= sortable.no_kamar %></td>
        <td><%= sortable.no_rm %></td>
        <td><%= sortable.nik %></td>
        <td><%= sortable.tgl_lahir%></td>
        <td><%= sortable.no_hp %></td>
        <td><%= sortable.agama%></td>
        <td><%= sortable.jenis_kelamin%></td>
        <td><%= sortable.alamat %></td>
        <td><%= sortable.pekerjaan %></td>
        <td><%= sortable.tgl_masuk%></td>
        <td><%= sortable.tgl_keluar%></td>
        <td><%= sortable.diagnosa %></td>
        <td><%= sortable.komorbid%></td>
        <td><%= link_to "show", @patient %></td>
        <td><%= link_to  "Edit", edit_patient_path(sortable) %></td>
        <td><%= link_to  "Delete", sortable, method: :delete, data: { confirm: 'Anda yakin mau dihapus?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>
</div>

 <%= will_paginate  %> 

</main>

app/views/patients/new.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
    
    <h1>Pasien Baru</h1>

    <%= render 'form', patient: @patient %>

    <%= link_to 'Back', patients_path %>


</main>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nama:</strong>
  <%= @patient.nama %>
</p>

<p>
  <strong>No kamar:</strong>
  <%= @patient.no_kamar %>
</p>

<p>
  <strong>No rm:</strong>
  <%= @patient.no_rm %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>